const AUTH_INITIALIZATION = 'AUTH_INITIALIZATION'
const AUTHENTICATED = 'AUTHENTICATED'
const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
const AUTHENTICATION_EXPIRED = 'AUTHENTICATION_EXPIRED'
const WALLETADDRESS_CHANGED = 'WALLETADDRESS_CHANGED'
const AUTHENTICATION_WALLET_CONNECTED = 'AUTHENTICATION_WALLET_CONNECTED'

const RECOMMENDED_INITIALIZATION = 'RECOMMENDED_INITIALIZATION'
const RECOMMENDED_LICENSE = 'RECOMMENDED_LICENSE'
const NOT_RECOMMENDED_LICENSE = 'NOT_RECOMMENDED_LICENSE'

export {
    AUTH_INITIALIZATION,
    AUTHENTICATED,
    NOT_AUTHENTICATED,
    AUTHENTICATION_EXPIRED,
    WALLETADDRESS_CHANGED,
    AUTHENTICATION_WALLET_CONNECTED,
    RECOMMENDED_INITIALIZATION,
    RECOMMENDED_LICENSE,
    NOT_RECOMMENDED_LICENSE,
}
