import {
    checkAuth,
    signout,
    getUser,
    verifySignature,
    sendCodeToPersonalEmail,
    sendCodeToPlatformEmail,
    checkPlatformCode,
    checkPersonalCode,
    resendEmail,
    signUpAsBuyer,
    spotifyLogin,
    getContactInfoOfOffer,
    checkIfLiked,
    likeOrDislikeLicense,
    searchArtists,
    getFavoriteLicenseIds,
    sendVerificationCodeToSpotifyEmail,
    sendVCodeToSpotifyEmail,
    verifySpotifyEmail,
    confirmUpdatedEmail,
    followArtist,
    unfollow,
    getFollower,
} from './user'
import {
    getPlayLists,
    searchByMulti,
    getMusicFromSpotify,
    getSongsOfAlbum,
    getAlbumsOfArtist,
    searchTracks,
} from './spotify'

import {
    saveListedLicenses,
    getGenres,
    searchNFTs,
    filterNFT,
    getOutGoingLicenses,
    getInComingLicenses,
    // updateRevenueSplits,
    checkduplication,
} from './listedLicenses'
import {
    uploadProfileImage,
    getPublicProfile,
    publishPublicProfile,
    unPublishPublicProfile,
    savePublicProfile,
    saveContactInfo,
    updateBuyerPlatform,
    getBuyerPlatform,
    getSellerPlatform,
    getCurrentAccount,
} from './profile'
import {
    storeSale,
    getSoldLicenses,
    getTrendingArtist,
    getTopArtist,
    getBurnedLicenses,
} from './soldLicenses'
import {
    getRecommendedLicense,
    deleteRecommendedLicense,
} from './recommendedLicenses'
import {
    createLicenseChangeNotification,
    markAsReadNotification,
    markAllAsReadNotification,
    createExpiredNotification,
} from './notification'

export {
    checkAuth,
    signout,
    getUser,
    verifySignature,
    sendCodeToPersonalEmail,
    sendCodeToPlatformEmail,
    checkPlatformCode,
    checkPersonalCode,
    resendEmail,
    signUpAsBuyer,
    spotifyLogin,
    getContactInfoOfOffer,
    searchArtists,
    getFavoriteLicenseIds,
    sendVerificationCodeToSpotifyEmail,
    sendVCodeToSpotifyEmail,
    verifySpotifyEmail,
    confirmUpdatedEmail,
    followArtist,
    unfollow,
    getFollower,
    // spotify
    getPlayLists,
    searchByMulti,
    getMusicFromSpotify,
    getSongsOfAlbum,
    getAlbumsOfArtist,
    searchTracks,
    // listed Licenses
    searchNFTs,
    saveListedLicenses,
    getGenres,
    filterNFT,
    getOutGoingLicenses,
    getInComingLicenses,
    // updateRevenueSplits,
    checkduplication,
    // profile
    uploadProfileImage,
    getPublicProfile,
    publishPublicProfile,
    unPublishPublicProfile,
    savePublicProfile,
    saveContactInfo,
    updateBuyerPlatform,
    getBuyerPlatform,
    getSellerPlatform,
    getCurrentAccount,
    // check if the user favorited the license
    checkIfLiked,
    // like the license
    likeOrDislikeLicense,
    // sold licenses
    storeSale,
    getSoldLicenses,
    getTrendingArtist,
    getTopArtist,
    getBurnedLicenses,
    // recommendedLicense
    getRecommendedLicense,
    deleteRecommendedLicense,
    // notification
    createLicenseChangeNotification,
    markAsReadNotification,
    markAllAsReadNotification,
    createExpiredNotification,
}
